# Generated by Django 4.1.7 on 2023-04-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='caractéristiques',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_iage',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'Audio'), ('LP', 'Laptops'), ('GM', 'Gaming'), ('TP', 'Téléphones'), ('TV', 'Televisions'), ('AC', 'Tablettes')], max_length=2),
        ),
    ]
