# Generated by Django 4.1.7 on 2023-04-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_composition_product_caractéristiques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'Audio'), ('LP', 'Laptops'), ('GM', 'Gaming'), ('TP', 'Téléphones'), ('TV', 'Televisions'), ('TB', 'Tablettes'), ('SH', 'Smart Home')], max_length=2),
        ),
    ]
