# Generated by Django 4.1.7 on 2023-04-21 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Béni Mellal-Khénifra', 'Béni Mellal-Khénifra'), ('Casablanca-Settat', 'Casablanca-Settat'), ('Dakhla-Oued Ed-Dahab', 'Dakhla-Oued Ed-Dahab'), ('Drâa-Tafilalet', 'Drâa-Tafilalet'), ('Fès-Meknès', 'Fès-Meknès'), ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'), ('Laâyoune-Sakia alHamra', 'Laâyoune-Sakia alHamra'), ('orientale', 'orientale'), ('Marrakech-Safi', 'Marrakech-Safi'), ('Rabat-Salé-Kénitra', 'Rabat-Salé-Kénitra'), ('Souss-Massa', 'Souss-Massa'), ('Tanger-Tétouan-Al Hoceima', 'Tanger-Tétouan-Al Hoceima')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
