# Generated by Django 4.1.7 on 2023-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'art'), ('LP', 'santé'), ('GM', 'informatique'), ('TP', 'economie'), ('TV', 'entreprise'), ('TB', 'enfants'), ('SH', 'Science')], max_length=2),
        ),
    ]
