# Generated by Django 4.1.7 on 2023-05-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
